### PR TITLE
(serveStatic plugin) Add an option to not append req.path() to the file path

### PR DESCRIPTION
**Pull request by rundef**
Hi,

I was kinda annoyed that the restify static plugin was behaving differently than the one in express.
Let me explain :

``` javascript
server.get(/^\/test\/.*$/, restify.serveStatic({
  directory: path.resolve(__dirname, '..', 'docs'),
  default: 'index.html'
}));
```

Here I expect that, when I make a request to _/test/document.html_, the plugin tries to serve me the content of _./docs/document.html_ - and not _./docs/test/document.html_ ... kind of like a symbolic link. 

So, the change I made, is to add an optional **appendRequestPath** option. The change is backward-compatible (it's set to true by default).

Additionally I fixed the **default file** test, which wasn't testing the right thing ... (it was making a request to _/dir/defaultfile.ext_ rather than _/dir/_)

### CODE REVIEW

**Comment by rundef** [comment]
I don't know why the tests are failing, it was working fine locally.
It doesn't seem related to my changes.

**Comment by micahr** [comment]
Thanks for the PR! Just a minor nit, your comment says that `appendRequestPath` is set to `false` by default, but the code indicates it's set to `true` when [not defined](https://github.com/restify/plugins/pull/41/files#diff-bb58f5dd87f90d4f9d8cab8ec02ec3c5R37). Setting it to true by default seems like the right thing based on the logic you wrote, just wanted to verify that was your intent.

Also, do you mind either adding another issue for documenting this new feature or updating the docs?

**Comment by rundef** [comment]
Yes, it should have been _true_ in my comment.

Sure I can update the docs. But I'm not sure where I should send the PR exactly ? In the **node-restify** project on the **5.x-docs** branch ?

**Comment by micahr** [comment]
The **5.x-docs** branch is perfect. Thanks so much!

**Comment by micahr** [comment]
Thanks again for the PR.

**Pull request merged**
