### PR TITLE
(serveStatic plugin) Do not leak file descriptors and always call next()

### PR DESCRIPTION
**Pull request by koute**
Fixes https://github.com/restify/plugins/issues/42

### CODE REVIEW

**Comment by koute** [comment]
@DonutEspresso Any ETA as to when you can take a look at this? (It has already been almost a week.) This is a fairly critical security fix.

**Comment by micahr** [comment]
LGTM thanks for the fix!

**Comment by koute** [comment]
@micahr Any chance you could publish a new package on NPM?

**Comment by micahr** [comment]
Sure

**Comment by micahr** [comment]
Version 1.0.3 has been published. Thanks again for your fix!

**Comment by DonutEspresso** [comment]
@koute apologies for not getting to this earlier. Thanks again for the contrib - much appreciated!

**Pull request merged**
