### PR TITLE
handle json derived content as text

### PR DESCRIPTION
**Pull request by vstirbu**
With this PR all `application/*+json` content gets the same treatment as `application/json`.

### CODE REVIEW

**Comment by retrohacker** [comment]
Hey @vstirbu,

Sorry for the radio silence on this PR. Thank you for putting in the time to create this!

I'm not sure why this change is necessary, though I don't doubt its importance. It may be helpful to some of us if we could get a test in `tests/*.js` that demonstrates when this change would be important. Ideally the test will fail in a meaningful way when your change is commented out, and pass when it is included.

Let me know if you need any guidance :heart:

For now, we are in the process of merging the plugins back into the main project's repo. I'm going to close this PR here. If the change is still important to you, please re-open it against that repo and we can discuss the tests there! :smile:

**Comment by vstirbu** [comment]
and the main project repo is https://github.com/restify/node-restify, right?

**Comment by retrohacker** [comment]
Yup :-) ! Sorry, I forgot to include that.

**Comment by vstirbu** [comment]
I've added a test to give the idea about the rationale of the change. Basically, the conversion from Buffer to string can be done in my own custom middleware but additional checks for text content are done already by the builtin body parser.

https://github.com/vstirbu/plugins/commit/010c69624fe4e6d23b51736031e8e959cb4b285d

**Comment by retrohacker** [comment]
That is super helpful @vstirbu!

It looks like most of the work to get this merged into the project is done :heart: the changes just need to be carried over to github.com/restify/node-restify!

**Comment by vstirbu** [comment]
Great! Do you need any help from my side?

**Comment by retrohacker** [comment]
If you could open the PR that would be a huge help :smile:

We are busy working on the 5.x release so it may be a bit before we have time to make progress on plugins otherwise.

**Pull request closed without merging**
