### PR TITLE
bringing over changes from core 5.x branch

### PR DESCRIPTION
**Pull request by DonutEspresso**
Needed to fully remove plugins from restify core.

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Upped a bunch of deps and pulled in changes from core since september. After this is done we can fully remove plugins from core. PTAL

**Comment by micahr** [comment]
:+1:

**Comment by DonutEspresso** [comment]
Thoughts on patch vs minor rev? Due to picking up assert-plus?

**Comment by micahr** [comment]
Patch should be fine, the api for restify didn't change.

**Pull request merged**
